### ISSUE TITLE
Saving after editing article - A critical error has occurred.

### ISSUE THREAD

**Issue by ghost** [ChrisHammond/dnnsimplearticle#1]
When saving an article after editing, the system displays error on front page "A critical error has occurred. See event log for more detail". The article that was edited does in fact save to the database. 
DNN Version: 08.00.04 (226)
Event log shows:

`AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:034c7964-27e2-489d-8f11-bf7dc28049c5
AssemblyVersion:8.0.4
PortalId:0
UserId:1
TabId:56
RawUrl:/Home/tabid/56/ctl/Edit/mid/494/aid/8/Default.aspx
Referrer:http://wcoaee.org/Home/tabid/56/ctl/Edit/mid/494/aid/8/Default.aspx
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
ExceptionHash:gWtXEK2E3zlG+h80bCz8BA==
Message:Data is Null. This method or property cannot be called on Null values.
StackTrace:
InnerMessage:Data is Null. This method or property cannot be called on Null values.
InnerStackTrace:
   at System.Data.SqlClient.SqlBuffer.get_String()
   at System.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at DotNetNuke.Entities.Content.ContentController.GetMetaData(Int32 contentItemId)
   at DotNetNuke.Entities.Content.Common.ContentExtensions.GetMetaData(ContentItem item, Int32 contentItemId)
   at DotNetNuke.Entities.Content.ContentItem.get_Metadata()
   at Christoc.Modules.dnnsimplearticle.Components.Taxonomy.Content.UpdateContentItem(Article objArticle, Int32 tabId)
   at Christoc.Modules.dnnsimplearticle.Components.ArticleController.SaveArticle(Article a, Int32 tabId)
   at Christoc.Modules.dnnsimplearticle.Edit.LbSaveClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: MCM-WEBSRV`

**Comment by ChrisHammond** [comment]
Do you have any categories defined? Wonder if that is erroring out

**Comment by ChrisHammond** [comment]
@tdgraham any chance you've got any additional info on this?

**Comment by ghost** [comment]
There are no categories defined. I did not see a place to add categories. Am I missing a part?

**Comment by ChrisHammond** [comment]
The categories are part of DNN itself. I'll have to try to dust the rust off and remember where those are managed, it's been a while

**Comment by ghost** [comment]
I found them under Taxonomy. Created a couple categories. Tried updating an existing article entry with the new category and still got the page load exception above and the category did not save with the article. If I create a new article and add a category it saves with the new article but when I try to edit the same article I get the page load exception.

**Comment by ChrisHammond** [comment]
I'm not able to recreate this at this time. If you're still experiencing this and can recreate please let me know
